### ISSUE TITLE
Streamline main4.md: ERC725, more. (Implement PE-Static B)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#115]
### Background

Ref: [PE-Static B Gslide](https://docs.google.com/presentation/d/1Bm9SKj6fvxpoVdjY70pShX70tUS11vwlZuTetkYHyI0/edit#slide=id.g2124915426e_1_0).

### TODOs for this issue

- [x] **Main thing: Support ERC725, by: support "Steps for competitor to submit" below. Tested.**
- [x] Ensure README mentions that we'll announce users via Desights
- [x] Ensure README has updated "what judges will do". Perhaps pull in predict-eth-judge, and retire that repo. Tested.
- [x] Ensure README has a link to discord, for dev support
- [x] ~~Ensure README has a link for user to submit feedback via GForm~~ Moved to [#117](https://github.com/oceanprotocol/predict-eth/issues/117)

### Appendix: Steps for competitor to submit (from Gslides)

1. encrypt predictions with judges' public key. (Why: so competition can't see)
2. create data nft
3. on data nft, set ERC725 key="predictions", value = encrypted predictions
4. send data nft to judges. (Why: so competitor can't change the values later)
5. Submission is eligible if step (4) is done before deadline (and other criteria met). We can check by simply reviewing transfers to judges on polygonscan (and at some point build an auto-check if we like)
