### ISSUE TITLE
Finish predict-eth round 3

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#119]
### TODOs

- [x] Compute nmses, using predict-eth-judge (modifying it as needed)
- [x] Start submissions GSheet. Incorporate info from DeSights
- [x] Manually review results, discuss, agree on winners
- [x] Write blog draft with results
- [x] Announce winner: write blog, publish it, do tweetstorm, share on social media. [predict-eth#128](https://github.com/oceanprotocol/predict-eth/issues/128)
- [x] [Ray] Send email to winners, showing ranking & handling invoicing
