### ISSUE TITLE
Do predict-eth round 4

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#121]
### TODOs - Before Launch

- [x] [Trent] Write first cut main4.md
- [x] [Trent] Streamline main4.md: ERC725, more. (Implement PE-Static B). [predict-eth#115](https://github.com/oceanprotocol/predict-eth/issues/115)
- [x] [Raymond] Create GForm for Round 4 feedback. Link to it in main4.md. [predict-eth#117](https://github.com/oceanprotocol/predict-eth/issues/117)
- [x] Register Predict-ETH Round 4 on Desights [predict-eth#130](https://github.com/oceanprotocol/predict-eth/issues/130)
- [x] Write & publish blog post announcing round 4. Tweet too. [predict-eth#127](https://github.com/oceanprotocol/predict-eth/issues/127)
- [x] Ensure end-to-end READMEs follow the updated steps / numbering of round 4 [predict-eth#126](https://github.com/oceanprotocol/predict-eth/issues/126)

### TODOs - During Contest

- [x] [Jaime, Veronica] Hold PE workshop midway through. Mar 14, 2023 at 3pm UTC
- [x] [Jaime, Veronica] Hold PE workshop a few days before deadline. Mar 28, 2023 at 3pm UTC

Bonus:
- [x] [Veronica] Hold "ocean-basics" workshop for newbies [predict-eth#122](https://github.com/oceanprotocol/predict-eth/issues/122)
- [x] [Veronica] Make a video of how to submit (random) predictions. Why: maximize chance of successful submission
[predict-eth#82](https://github.com/oceanprotocol/predict-eth/issues/82)

### TODOs - After Contest Closes

- [x] [Trent] Start submissions Gsheet. **[HERE](https://docs.google.com/spreadsheets/d/15tOK5W3ve0xyL2kI99ixxYdBIvX12hTHBbyCVY46Fw4/edit#gid=266847751)**. 
- [x] [Trent] Have Manan share Desights info. **[HERE](https://docs.google.com/spreadsheets/d/1WSp--0nygtOzCiZmCqQt9V7jjGzW9NOim2VKqNG-wVw/edit#gid=1484720093)**. [Slack thread](https://oceanprotocol.slack.com/archives/C04U7GJN9LG/p1680787308129229).
- [x] [Trent] port Desights info into submissions GSheet
- [x] [Trent] Compute nmses, via predict-eth-judge / predict-eth / other. Populate GSheet. [Slack report](https://oceanprotocol.slack.com/archives/C047QMC1Z4G/p1681108063283289)
- [x] [Trent] Start PE round 5 issue: copy & paste this one into a new issue, with appropriate zenhub column, priority label, etc. [Github](https://github.com/oceanprotocol/predict-eth/issues/132), [Zenhub](https://app.zenhub.com/workspaces/s2---challenges--oceanpy-63fdd705943eac001b12f49f/issues/gh/oceanprotocol/predict-eth/132).
- [x] [all] In slack, manually review results, discuss, agree on winners. (Should be fast)
- [x] [Veronica, Christian] Write blog draft with results
- [x] [Veronica, Christian] Publish results: blog, twitter.
- [x] Announce winner: write blog, publish it, do tweetstorm, share on social media
- [x] Send email to winners, showing ranking & handling invoicing
