### ISSUE TITLE
Update main4.md for using desights

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#125]
### Background / Motivation

In the end, we _do_ want to use Desights for Predict-eth Round 4. (Details below). 

### TODOs

Add to main4.md:
- [ ] checklist at beginning has Desights
- [ ] a step 0 where the user signs up to desights // registers for the contest
- [ ] a final step where they copy the txid from the python output and enter it into a desights form.

### Appendix: Motivations, Detailed

From [this slack msg](https://oceanprotocol.slack.com/archives/C047QMC1Z4G/p1677747753072569) by trentmc:

Hi all, I had a very good chat yesterday with Manan Re Desights and predict-eth.
Manan helped me to see:

- maybe Desights adds a bit more friction for submission
- _but_ it reduces friction / churn because it has excellent support in case there are issues. (By getting you to join the discord as part of sign-up. Manan described how for round 3, the discord age related 1:1s were critical to many entries getting submitted).
- So, _overall_ friction is lower.

And, Manan has great interest for Desights to be part of submission for predict-eth. He'd accept if no, but he indicated his great preference to be involved.

So then we discussed: if we did have Desights for predict-eth submissions, how might we keep the friction low? Tactics emerged:

- don't require an admin to give you access
- in sign-up, name and email are optional. And no other fields needed either. But you still do need to join the desights discord, since this really helps if issues. (And of course when you sign up, it's registering the address of the wallet that you connected with.)
- to submit, only one thing needed: the txid of the final tx in following the README flow. (This is the tx where the competitor sends the data nft to the judges.)

If we did have Desights for predict-eth submissions, then the README would get this added:

- a step 0 where the user signs up to desights // registers for the contest
- a final step where they copy the txid from the python output and enter it into a desights form.

Manan and I had talked this through and arrived at this overall design proposal. I like it, a lot! Because it is best wrt friction, and helps Desights in the loop.

Therefore, I propose that we do have Desights for predict-eth submissions, with the changes above. Any objections?

[there were no objections]
