### ISSUE TITLE
Do predict-eth round 5

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#132]
### TODOs - Before Launch

Predict-ETH Round 5 - predictions due Wed May 3, 2023

- [x] Discuss & decide tweaks for round 5
   - [YES - do] Every hour for 12 h --> Every 5 min x 12 for 60 min total. Why: closer to Predictoor. tlm recommend: yes, because low diff wrt Predictoor. (All agreed to 5 min). (For "NO" ideas see appendix below)
- [x] [Jaime] Write first cut main5.md as copy of main4.md. Update main5.md and & end-to-end READMEs to reflect tweaks for round 5 (5 min not 60). [predict-eth#133](https://github.com/oceanprotocol/predict-eth/issues/133)
- [x] [T] Register round 5 on Desights 
- [x] [T] Write & publish [blog post](https://blog.oceanprotocol.com/predict-eth-round-data-challenge-5-is-live-d42ca8cf6af0) announcing round 5. [Tweet too](https://twitter.com/oceanprotocol/status/1649081604906655746). 

### TODOs - During Contest

- [x] [Jaime] Hold PE workshop: Tue Apr 25 at 3PM UTC (8 days before deadline of Wed May 3).

### TODOs - After Contest Closes

- [x] [T] Compute nmses & winners, via predict-eth-judge. 
  - [GFolder](https://drive.google.com/drive/u/1/folders/1SGSm1J1dJa1UQzBwAoch2amCahjhd1I5)
  - [Full pej output - GDoc](https://docs.google.com/document/d/17xoFeWk-lKZB7VxVcnAAm12F57-w3PsNbudCJ-W39Dw/edit)
  - [Winners summary - GDoc](https://docs.google.com/document/d/1XGWsW2mceCQ0d_g-0nDwQPRTBjU9aa44iQvjgYiGV6Y/edit)
- [x] [T] Write blog draft with results. [Draft](https://medium.com/@TeamOcean/here-are-the-winners-of-the-predict-eth-round-5-data-challenge-95f71bcade95).
- [x] [T] Get image from Casiana
- [x] [T] Publish results: [blog](https://medium.com/@TeamOcean/here-are-the-winners-of-the-predict-eth-round-5-data-challenge-95f71bcade95), [twitter](https://twitter.com/oceanprotocol/status/1654305062062264321).
- [x] [T] Pay winners, let them know. How: send OCEAN to wallet. Tweet/medium is enough. T [asked Alex](https://oceanprotocol.slack.com/archives/DNVRWS6LQ/p1683250963318539) Alex May 5; Alex did it May 5
- [x] [T] Create github issue for Predict-ETH Round 6, and initialize it from _this_ issue. [Link](https://github.com/oceanprotocol/predict-eth/issues/136)

### Appendix: Round 4 info

- [Round 4 Github issue](https://github.com/oceanprotocol/predict-eth/issues/121)
- [Round 4 Submissions GSheet](https://docs.google.com/spreadsheets/d/15tOK5W3ve0xyL2kI99ixxYdBIvX12hTHBbyCVY46Fw4/edit#gid=409196824)
- [Round 4 GFolder](https://drive.google.com/drive/u/1/folders/1i0LxCYAzPtoyQzXRvCWC5WDzazZp988t)
- Round 4 results announcement: [blog](https://blog.oceanprotocol.com/here-are-the-winners-of-the-predict-eth-round-4-data-challenge-1672b36c0af9), [twitter](https://twitter.com/oceanprotocol/status/1646548091275804672)

### Appendix: Possible changes discussed that we're _not_ implementing now

- [NO - don't do] 250 OCEAN bonus for just going through flow. Why: incentivize more. tlm recommend: no, because round 4 didn't have it yet we had 26 submissions (19 valid). Discussed, agreed to not do
- [NO - don't do yet] Be able to predict at different times. Rather than having to be up at midnight. Discussed & agreed to do, but not yet, since Trent & Jaime's time is better used elsewhere 
- [NO - don't do yet] Rather than just predict 5 min in advance, also do 10 min, 20 min, 30 min, 1h, 2h, .. . Discussed & agreed to do in Predictoor at some point, and maybe competition, but not at this point in time
