### ISSUE TITLE
Do predict-eth round 6

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#136]
### TODOs - Before Launch

Predict-ETH Round 6 - predictions due Wed Jun 7, 2023 at 23.59 UTC

- [x] [T] Write main6.md as copy of main5.md, with minimal tweaks. 
- [ ] [T] Write & publish blog post announcing round 5. Tweet too. 

### TODOs - During Contest

- [ ] [Jaime] Hold PE workshop: Tue May 30 at 3PM UTC (8 days before deadline of Wed Jun 7).

### TODOs - After Contest Closes

- [ ] [T] Compute nmses & winners, via predict-eth-judge. 
  - [GFolder](https://drive.google.com/drive/u/1/folders/13SVd_Ur481AMWdoG9SDIHBWaTuPV90P-)
  - [Full pej output - GDoc - FIXME]
  - [Winners summary - GDoc - FIXME]
- [ ] [T] Write blog draft with results. [Draft - FIXME]
- [ ] [T] Get image from Casiana
- [ ] [T] Publish results: [blog - FIXME], [twitter - FIXME]
- [ ] [T] Pay winners, let them know. How: send OCEAN to wallet. Tweet/medium is enough. [T ask Alex: give # OCEAN and target address, for top 3]
- [ ] [T] Create github issue for Predict-ETH Round 7, and initialize it from _this_ issue. (Or are we porting to DF for round 7?)

### Appendix: Round 5 info

- [Round 5 Github issue](https://github.com/oceanprotocol/predict-eth/issues/132)
- [Round 5 GFolder](https://drive.google.com/drive/u/1/folders/1SGSm1J1dJa1UQzBwAoch2amCahjhd1I5)
- Round 5 results announcement: [blog](https://medium.com/@TeamOcean/here-are-the-winners-of-the-predict-eth-round-5-data-challenge-95f71bcade95), [twitter](https://twitter.com/oceanprotocol/status/1654305062062264321)
