### ISSUE TITLE
Do predict-eth round 7

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#137]
### TODOs - Before Launch

Predict-ETH Round X=7. Predictions due Wed Jun 7, 2023 at 23.59 UTC. X-1=5, X+1=7.

- [] [T] Write mainX.md as copy of main(X-1).md, with minimal tweaks. 
- [ ] Write & publish blog post announcing round X. [Link: FIXME]
- [ ] Tweet. [Link: FIXME]
- [ ]  In marcom-wg, let channel know. And, ask Casiana / marcom to add new round X to site

### TODOs - During Contest

(_not_ doing a workshop this round)

### TODOs - After Contest Closes

- [ ] [T] Compute nmses & winners, via predict-eth-judge. 
  - [GFolder Link : FIXME]
  - [Full pej output - GDoc - FIXME]
  - [Winners summary - GDoc - FIXME]
- [ ] [T] Write blog draft with results. [Draft - FIXME]
- [ ] [T] Get image from Casiana
- [ ] [T] Publish results: [blog - FIXME], [twitter - FIXME]
- [ ] [T] Pay winners, let them know. How: send OCEAN to wallet. Tweet/medium is enough. [T ask Alex: give # OCEAN and target address, for top 3]
- [ ] [T] Create github issue for Predict-ETH Round (X+1), and initialize it from _this_ issue. (Unless we're porting to Challenge DF for round next round)

### Appendix: Round (X-1) info

(Round X - 1 = Round 6)

- Round X-1 Github issue: [Link](https://github.com/oceanprotocol/predict-eth/issues/132)
- Round X-1 GFolder: [Link FIXME]
- Round X-1 results blog: [Link FIXME]
- Round X-1 results twitter: [Link FIXME]
