### ISSUE TITLE
 Update predict-eth repo to reflect new nmse calcs; do new release

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#143]
### Background / motivation

df-py/df_py/challenge/nmse.py has `calc_nmse()` to calculate the nmse. (And it tests/test_nmse.py to test the results).

Issue [df-py#696](https://github.com/oceanprotocol/df-py/issues/696) was recently completed. [Here's](https://github.com/oceanprotocol/df-py/commit/cd70229dbb97d45cb17e6227e00700afe70ecca6) the commit. It updated df-py's `calc_nmse()` by re-scaling things. Now, nmse values are more sane. (It doesn't affect winners.) 

### TODOs

- [x] In predict-eth repo, update its separate implementation of `calc_nmse()`, to be in sync with the one in df-py
- [x] Update predict-eth READMEs if needed
- [x] Do a new release of df-py to pypi
