### ISSUE TITLE
Predict ETH round two

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#3]
## Motivation

Ocean is focusing on DeFi, specifically DeFi traders, more specifically the Python-savvy data scientists doing algorithmic trading. Towards this, we have series of Data Bounties to predict ETH price. The [ocean.py predict-eth.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/predict-eth.md) README supported the first Data Bounty. The predict-eth2.md README will support the second. And so on.

We use these bounties, with key support from the READMEs - as the internal customer towards serving DeFi traders, to help us prioritize work across the Ocean stack, from Aquarius and Provider to ocean.py and ocean.js.

_This_ epic tees up for the second challenge.

Overall aim: reduce friction to competitors doing the challenge and getting better prediction results. For the second challenge, this includes showing a baseline approach to build a model from data feed(s), and providing more input data from a greater variety of sources. Future predict-eth READMEs will start to incorporate C2D.

## TODOs

Jaime (@jfdelgad):
- [x] in eth-predict2.md, do a simple model-based prediction (eg linear model from scikit learn). As part of this: write the code that uses just the 1 provided dataset. [eth-predict#4](https://github.com/oceanprotocol/predict-eth/issues/4)
- [x] change ocean.py [graphql readme](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/publish-flow-graphql.md): eth/usdt on TheGraph [ocean.py#1029](https://github.com/oceanprotocol/ocean.py/issues/1029)
- [x] change [on-chain readme](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/publish-flow-onchain.md): eth/usdt on uniswap [ocean.py#1030](https://github.com/oceanprotocol/ocean.py/issues/1030)
- [x] publish asset: eth/usdt on TheGraph (graphql), into Polygon. Update eth-predict2.md to also load it [predict-eth#6](https://github.com/oceanprotocol/predict-eth/issues/6)
- [x] Improve model-based prediction. More datasets, more feature vectors, or better AI models [predict-eth#8](https://github.com/oceanprotocol/predict-eth/issues/8)

JP (@juanpablovs):
- [x] publish asset: btc/usdt on Ocean CEXA, into Polygon. Update eth-predict2.md to also load it [predict-eth#9](https://github.com/oceanprotocol/predict-eth/issues/9)
- [x] publish asset: btc/usdt on TheGraph (graphql), into Polygon. Update eth-predict2.md to also load it  [predict-eth#10](https://github.com/oceanprotocol/predict-eth/issues/10)
- [x] Improve model-based prediction. More datasets, more feature vectors, or better AI models [predict-eth#12](https://github.com/oceanprotocol/predict-eth/issues/12)

Jaime and JP:
- [x] write + publish blog post "ML to predict the price of ETH: Part One", similar to the one on "to predict price of BTC". Describe what didn't work / mistakes.
- [ ] write + publish blog post ".. : Part Two",

Trent (@trentmc):
- [x] Start predict-eth2.md template, in new repo [pm#180](https://github.com/oceanprotocol/pm/issues/180)
- [x] Change contest rules: <24h ahead. This is more feasible, and more practical for people trying to predict ETH and make $ [ocean.py#1021](https://github.com/oceanprotocol/predict-eth/issues/1)
- [x] Fix problem: predict-eth.md predictions show up in Ocean Market  [ocean.py#1022](https://github.com/oceanprotocol/ocean.py/issues/1022)
- [x] Split apart contest instructions README from possible approaches to solve [predict-eth#21](https://github.com/oceanprotocol/predict-eth/issues/21)
