### ISSUE TITLE
Support competitions for dynamic predictions, via C2D asset & dynamic judging service. (Implement PE-Static C & PE-Dynamic A)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#40]
### Motivation

Overall: get competitors to submit C2D-alg that gives predictions upon request; be able to measure results. In other words, implement PE-Static-C and PE-Dynamic-A. (PE = Predict-ETH)

Key details are in [predict-eth planning slides](https://docs.google.com/presentation/d/1Bm9SKj6fvxpoVdjY70pShX70tUS11vwlZuTetkYHyI0/edit#slide=id.g114755ae868_0_0). Please review slides on PE-Static C and PE-Dynamic A before proceeding.

### TODOs for this issue

PE-Static C builds on PE-Dynamic A. So implement PE-Dynamic A first.

Specific TODOs:

- [ ] Write README for "PE-Dynamic A" competition. It follows the setup [in the GSlides](https://docs.google.com/presentation/d/1Bm9SKj6fvxpoVdjY70pShX70tUS11vwlZuTetkYHyI0/edit#slide=id.g2124915426e_0_0). It should work end-to-end. This includes:
  - [ ] Create a super-basic C2D algorithm that predicts 10 minutes ahead. This will be helpful as the README is created. 
  - [ ] Write the bulk of the README, in line with the setup in the Gslides
  - [ ] Ensure it includes a new "what judges do" section in the README. Why: so competitors know what judging looks like - and to test on their own C2D algs. And this will include: **Set up a new OPF "dynamic judging" service** that will run right after a competition deadline. It runs each of the C2D algs every ten minutes, for 12 hours, and then computes nmse. (Bolded because this work is not trivial.) 
- [ ] Once PE-Dynamic A README is ready, do PE-Static C. How: work backwards to inject in the C2D elements into PE-Static, by creating a README for PE-Static C. It can start with the most recent competition (mainx.md to submit static predictions), and add in C2D stuff of PE-Dynamic A.

**Comment by trentmc** [comment]
UPDATE: I have devised a cleaner, simpler way to achieve the same goals of this ticket. I'm working on that elsewhere. Therefore, I will close _this_ issue.
